# Generated by Django 2.2.6 on 2019-11-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=4096)),
                ('hidden_address', models.CharField(max_length=512)),
                ('is_paid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EarlyAssignmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=4096)),
                ('proxy_id', models.CharField(max_length=4096)),
                ('verification_key', models.CharField(max_length=1024)),
                ('timestamp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpireTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_timestamp', models.IntegerField()),
                ('callback_info', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_id', models.CharField(max_length=4096)),
                ('verification_key', models.CharField(max_length=1024)),
                ('site_key', models.CharField(max_length=1024)),
                ('current_reputation', models.FloatField()),
                ('is_advertising', models.BooleanField()),
                ('hidden_address', models.CharField(max_length=512)),
                ('avail_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_id', models.CharField(max_length=4096)),
                ('votes', models.FloatField()),
                ('timestamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReputationTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=4096)),
                ('tag_id', models.IntegerField()),
                ('vote', models.IntegerField()),
                ('timestamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_pem', models.CharField(max_length=8192)),
                ('expire', models.FloatField()),
                ('key_type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UsedTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_serial', models.CharField(max_length=4096)),
                ('insert_time', models.FloatField()),
            ],
        ),
    ]
