# Generated by Django 2.2.6 on 2019-10-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=4092)),
                ('hidden_address', models.CharField(max_length=512)),
                ('valid_from', models.IntegerField()),
                ('valid_until', models.IntegerField()),
            ],
        ),
    ]
